
[ClassVersion("1.0.0.0"), FriendlyName("xDatabaseLogin")]
class MSFT_xDatabaseLogin : OMI_BaseResource
{
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key] String LoginName;
    [Write] String LoginPassword;
    [Required, ValueMap{"Windows","SQL"}, Values{"Windows","SQL"}] string SqlAuthType;
    [Required, Description("Sql Server Name")] String SqlServer;
    [Write, EmbeddedInstance("MSFT_Credential")] String SqlConnectionCredential;
};




