---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'\""
  extras:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="3.7.0"
Gemfile:
  supports_windows: true
  required:
    ':development':
      - gem: rspec
        version: '~>2.14.1'
      - gem: puppet-lint
      - gem: puppetlabs_spec_helper
        version: '~>0.10.3'
      - gem: puppet_facts
      - gem: mocha
        version: '~>0.10.5'
      - gem: puppet-blacksmith
    ':system_tests':
      - gem: beaker
      - gem: master_manipulator
        version: '1.1.2'
    ':build':
      - gem: 'librarian-repo'
        git: 'https://github.com/msutter/librarian-repo.git'
      - gem: cim
      - gem: mof
        git: 'https://github.com/puppetlabs/mof.git'
      - gem: charlock_holmes
      - gem: iconv
        version: '~> 1.0.4'
        condition: "RUBY_VERSION >= '2.0'"
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
.gitignore:
  paths:
  - 'bin'
  - 'import'
  - '.tmp'
  - '.rbenv-gemsets'
  - '.ruby-version'
  - '*.lock'
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 193
    - PUPPET_GEM_VERSION: 3.7.0
      RUBY_VER: 200-x64
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests build"
  test_script:
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
