
[ClassVersion("1.0.0.0"), FriendlyName("xBLAutoBitlocker")]
class MSFT_xBLAutoBitlocker : OMI_BaseResource
{
    //Used to automatically enable Bitlocker on drives of type Fixed or Removable. Does not work on Operating System drives.

    [Key, ValueMap{"Fixed","Removable"}, Values{"Fixed","Removable"}] String DriveType; //The type of volume, as reported by Get-Volume, to auto apply Bitlocker to
    [Write] Sint32 MinDiskCapacityGB; //If specified, only disks this size or greater will auto apply Bitlocker
    [Required, ValueMap{"PasswordProtector","RecoveryPasswordProtector","StartupKeyProtector","TpmProtector"}, Values{"PasswordProtector","RecoveryPasswordProtector","StartupKeyProtector","TpmProtector"}] String PrimaryProtector;
    [Write] Boolean AutoUnlock; //Whether volumes should be enabled for auto unlock using Enable-BitlockerAutoUnlock

    //Remaing properties correspond directly to Enable-Bitlocker parameters
    //http://technet.microsoft.com/en-us/library/jj649837.aspx
    [Write] String AdAccountOrGroup;
    [Write] Boolean AdAccountOrGroupProtector;
    [Write, ValueMap{"Aes128","Aes256"}, Values{"Aes128","Aes256"}] String EncryptionMethod;
    [Write] Boolean HardwareEncryption;
    [Write, EmbeddedInstance("MSFT_Credential")] String Password; //NOTE: Username doesn't matter for the credential. Just put the Password in the Password field
    [Write] Boolean PasswordProtector;
    [Write, EmbeddedInstance("MSFT_Credential")] String Pin; //NOTE: Username doesn't matter for the credential. Just put the Pin in the Password field
    [Write] String RecoveryKeyPath;
    [Write] Boolean RecoveryKeyProtector;
    [Write] Boolean RecoveryPasswordProtector;
    [Write] Boolean Service;
    [Write] Boolean SkipHardwareTest;
    [Write] String StartupKeyPath;
    [Write] Boolean StartupKeyProtector;
    [Write] Boolean TpmProtector;
    [Write] Boolean UsedSpaceOnly;
};


