
[ClassVersion("1.0.0.0"), FriendlyName("xRDSessionDeployment")]
class MSFT_xRDSessionDeployment : OMI_BaseResource
{
    [key, Description("Specifies the FQDN of a server to host the RD Session Host role service. ")] string SessionHost;
    [key, Description("Specifies the FQDN of a server to host the RD Connection Broker role service.")] string ConnectionBroker;
    [key, Description("Specifies the FQDN of a server to host the RD Web Access role service. ")] string WebAccessServer;
};



