
[ClassVersion("1.0.0.0"), FriendlyName("xSmaCredential")]
class MSFT_xSmaCredential : OMI_BaseResource
{
    [Key, Description("Name of credential.")] String Name;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credential object to be imported.")] String credential;
    [Write, Description("Description of credential.")] String Description;
    [Required, Description("Web service endpoint of SMA instance.")] String WebServiceEndpoint;
    [Write, Description("Port to reach the web service endpoint.")] Uint32 Port;
    [Read, Description("User name of credential found within SMA")] String UserName;
};

