
[ClassVersion("1.0.0"),FriendlyName("xMySqlServer")] 
class MSFT_xMySqlServer : OMI_BaseResource
{
  [Key, Description("Provides the service name to use during setup of MySQL")]
  String ServiceName;
  
  [ValueMap{"Present", "Absent"},Values{"Present", "Absent"},
  Description("Ensure resource is present or absent")]
  String Ensure;
  
  [required,
  write,
  EmbeddedInstance("MSFT_Credential"),
  Description("The root credential that is used to install mySql server.")]
  String RootPassword;
};


