[ClassVersion("1.0.0.0"), FriendlyName("xDFSReplicationGroup")]
class MSFT_xDFSReplicationGroup : OMI_BaseResource
{
    [Key, Description("The name of the DFS Replication Group.")] String GroupName;
    [Required, Description("Specifies whether the DSF Replication Group should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("A description for the DFS Replication Group.")] String Description;
    [Write, Description("A list of computers that are members of this Replication Group. These can be specified using either the ComputerName or FQDN name for each member. If an FQDN name is used and the DomainName parameter is set, the FQDN domain name must match.")] String Members[];
    [Write, Description("A list of folders that are replicated in this Replication Group.")] String Folders[];
    [Write, Description("This allows a replication topology to assign to the Replication Group. It defaults to Manual, which will not automatically create a topology. If set to Fullmesh, a full mesh topology between all members will be created."), ValueMap{"Fullmesh","Manual"}, Values{"Fullmesh","Manual"}] String Topology;
    [Write, Description("An array of DFS Replication Group Content Paths to use for each of the Folders. This can have one entry for each Folder in the Folders parameter and should be set in th same order. If any entry is not blank then the Content Paths will need to be set manually by using the xDFSReplicationGroupMembership resource.")] String ContentPaths[];
    [Write, Description("The AD domain the Replication Group should created in.")] String DomainName;
};
