
[ClassVersion("1.0.0.0"), FriendlyName("xAzureAffinityGroup")]
class MSFT_xAzureAffinityGroup : OMI_BaseResource
{
    [key, Description("Specifies a name for the new affinity group that is unique to the subscription.")] string Name;
    [write, Description("Specifies whether the Azure Affinity Group should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [required, Description("Specifies the geographical location of the data center where the affinity group will be created.  This must match a value from the Name property of objects returned by Get-AzureLocation.")] string Location;
    [write, Description("Specifies a description for the affinity group. The description may be up to 1024 characters in length. ")] string Description;
    [write, Description("Specifies a label for the affinity group. The label may be up to 100 characters in length. ")] string Label;
};


