[ClassVersion("1.0.0.0"), FriendlyName("RunbookDirectory")]
class MSFT_xRunbookDirectory : OMI_BaseResource
{
    [Required, Description("The import state of runbooks found at RunbookPath. This can be Published, Draft, or Absent"), ValueMap{"Published","Draft","Absent"}, Values{"Published","Draft","Absent"}] String Ensure;    
    [Key, Description("Path to Runbook(s) to be imported. Accepts wildcards.")] String RunbookPath;
    [Read, Description("Describes the validity of the imported Runbook(s).")] Boolean Matches;
    [Key, Description("URL of SMA's web service endpoint.")] String WebServiceEndpoint;
    [Write, Description("Port of the SMA web site. Defaults to the SMA default of 9090.")] Uint32 Port;
};

