
[ClassVersion("0.1.0.0"), FriendlyName("xMpPreference")]
class MSFT_xMpPreference : OMI_BaseResource
{
    [Key, Description("Provide the text string to uniquely identify this group of settings")] String Name;
    [Write, Description("Specifies an array of file paths to exclude from scheduled and real-time scanning. You can specify a folder to exclude all the files under the folder.")] String ExclusionPath[];
    [Write, Description("Specifies an array of file name extensions, such as obj or lib, to exclude from scheduled, custom, and real-time scanning.")] String ExclusionExtension[];
    [Write, Description("Specifies an array of processes, as paths to process images. The cmdlet excludes any files opened by the processes that you specify from scheduled and real-time scanning. Specifying this parameter excludes files opened by executable programs only. The cmdlet does not exclude the processes themselves. To exclude a process, specify it by using the ExclusionPath parameter.")] String ExclusionProcess[];
    [Write, Description("Specifies scanning configuration for incoming and outgoing files on NTFS volumes. Specify a value for this parameter to enhance performance on servers which have a large number of file transfers, but need scanning for either incoming or outgoing files. Evaluate this configuration based on the server role. For non-NTFS volumes, Windows Defender performs full monitoring of file and program activity."), ValueMap{"Both","Incoming","Outgoing"}, Values{"Both","Incoming","Outgoing"}] String RealTimeScanDirection;
    [Write, Description("Specifies the number of days to keep items in the Quarantine folder. If you specify a value of zero or do not specify a value for this parameter, items stay in the Quarantine folder indefinitely.")] uint32 QuarantinePurgeItemsAfterDelay;
    [Write, Description("Specifies the day of the week on which to perform a scheduled full scan in order to complete remediation. Alternatively, specify everyday for this full scan or never. The default value is Never. If you specify a value of Never or do not specify a value, Windows Defender performs a scheduled full scan to complete remediation by using a default frequency."), ValueMap{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}, Values{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}] String RemediationScheduleDay;
    [Write, Description("Specifies the time of day, as the number of minutes after midnight, to perform a scheduled scan. The time refers to the local time on the computer. If you do not specify a value for this parameter, a scheduled scan runs at the default time of two hours after midnight.")] DateTime RemediationScheduleTime;
    [Write, Description("Specifies the number of minutes before a detection in the additional action state changes to the cleared state.")] uint32 ReportingAdditionalActionTimeOut;
    [Write, Description("Specifies the number of minutes before a detection in the non-critically failed state changes to the cleared state.")] uint32 ReportingNonCriticalTimeOut;
    [Write, Description("Specifies the number of minutes before a detection in the critically failed state changes to either the additional action state or the cleared state.")] uint32 ReportingCriticalFailureTimeOut;
    [Write, Description("Specifies the maxium percentage CPU usage for a scan. The acceptable values for this parameter are:  integers from 5 through 100, and the value 0, which disables CPU throttling. Windows Defender does not exceed the percentage of CPU usage that you specify. The default value is 50.")] uint32 ScanAvgCPULoadFactor;
    [Write, Description("Indicates whether to check for new virus and spyware definitions before Windows Defender runs a scan. If you specify a value of $True, Windows Defender checks for new definitions. If you specify $False or do not specify a value, the scan begins with existing definitions. This value applies to scheduled scans and to scans that you start from the command line, but it does not affect scans that you start from the user interface.")] boolean CheckForSignaturesBeforeRunningScan;
    [Write, Description("Specifies the number of days to keep items in the scan history folder. After this time, Windows Defender removes the items. If you specify a value of zero, Windows Defender does not remove items. If you do not specify a value, Windows Defender removes items from the scan history folder after the default length of time, which is 30 days.")] uint32 ScanPurgeItemsAfterDelay;
    [Write, Description("Indicates whether to start scheduled scans only when the computer is not in use. If you specify a value of $True or do not specify a value, Windows Defender runs schedules scans when the computer is on, but not in use.")] boolean ScanOnlyIfIdleEnabled;
    [Write, Description("Specifies the scan type to use during a scheduled scan. If you do not specify this parameter, Windows Defender uses the default value of quick scan."), ValueMap{"FullSCan","QuickScan"}, Values{"FullSCan","QuickScan"}] String ScanParameters;
    [Write, Description("Specifies the day of the week on which to perform a scheduled scan. Alternatively, specify everyday for a scheduled scan or never. If you specify a value of Never or do not specify a value, Windows Defender performs a scheduled scan by using a default frequency."), ValueMap{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}, Values{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}] String ScanScheduleDay;
    [Write, Description("Specifies the time of day, as the number of minutes after midnight, to perform a scheduled quick scan. The time refers to the local time on the computer. If you do not specify a value for this parameter, a scheduled quick scan runs at the time specified by the ScanScheduleTime parameter. That parameter has a default time of two hours after midnight.")] DateTime ScanScheduleQuickScanTime;
    [Write, Description("Specifies the time of day, as the number of minutes after midnight, to perform a scheduled scan. The time refers to the local time on the computer. If you do not specify a value for this parameter, a scheduled scan runs at a default time of two hours after midnight.")] DateTime ScanScheduleTime;
    [Write, Description("Specifies a grace period, in minutes, for the definition. If a definition successfully updates within this period, Windows Defender abandons any service initiated updates. This parameter overrides the value of the CheckForSignaturesBeforeRunningScan parameter.")] uint32 SignatureFirstAuGracePeriod;
    [Write, Description("Specifies a grace period, in minutes, for the definition. If a definition successfully updates within this period, Windows Defender abandons any service initiated updates.")] uint32 SignatureAuGracePeriod;
    [Write, Description("Specifies file-share sources for definition updates. Specify sources as a bracketed sequence of Universal Naming Convention (UNC) locations, separated by the pipeline symbol. If you specify a value for this parameter, Windows Defender attempts to connect to the shares in the order that you specify. After Windows Defender updates a definition, it stops attempting to connect to shares on the list. If you do not specify a value for this parameter, the list is empty.")] String SignatureDefinitionUpdateFileSharesSources;
    [Write, Description("Indicates whether to initiate definition updates even if no antimalware engine is present. If you specify a value of $True or do not specify a value, Windows Defender initiates definition updates on startup. If you specify a value of $False, and if no antimalware engine is present, Windows Defender does not initiate definition updates on startup.")] boolean SignatureDisableUpdateOnStartupWithoutEngine;
    [Write, Description("Specifies the order in which to contact different definition update sources. Specify the types of update sources in the order in which you want Windows Defender to contact them, enclosed in braces and separated by the pipeline symbol.")] String SignatureFallbackOrder;
    [Write, Description("Specifies the day of the week on which to check for definition updates. Alternatively, specify everyday for a scheduled scan or never. If you specify a value of Never or do not specify a value, Windows Defender checks for definition updates by using a default frequency."), ValueMap{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}, Values{"Everyday","Never","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"}] String SignatureScheduleDay;
    [Write, Description("Specifies the time of day, as the number of minutes after midnight, to check for definition updates. The time refers to the local time on the computer. If you do not specify a value for this parameter, Windows Defender checks for definition updates at the default time of 15 minutes before the scheduled scan time.")] DateTime SignatureScheduleTime;
    [Write, Description("Specifies the number of days after which Windows Defender requires a catch-up definition update. If you do not specify a value for this parameter, Windows Defender requires a catch-up definition update after the default value of one day.")] uint32 SignatureUpdateCatchupInterval;
    [Write, Description("Specifies the interval, in hours, at which to check for definition updates. The acceptable values for this parameter are:  integers from 1 through 24. If you do not specify a value for this parameter, Windows Defender checks at the default interval. You can use this parameter instead of the SignatureScheduleDay parameter and SignatureScheduleTime parameter. ")] uint32 SignatureUpdateInterval;
    [Write, Description("Specifies the type of membership in Microsoft Active Protection Service. Microsoft Active Protection Service is an online community that helps you choose how to respond to potential threats. The community also helps prevent the spread of new malicious software. If you join this community, you can choose to automatically send basic or additional information about detected software. Additional information helps Microsoft create new definitions. In some instances, personal information might unintentionally be sent to Microsoft. However, Microsoft will not use this information to identify you or contact you."), ValueMap{"Advanced","Basic","Disabled"}, Values{"Advanced","Basic","Disabled"}] String MAPSReporting;
    [Write, Description("Indicates whether to disable privacy mode. Privacy mode prevents users, other than administrators, from displaying threat history.")] boolean DisablePrivacyMode;
    [Write, Description("Indicates whether to select a random time for the scheduled start and scheduled update for definitions. If you specify a value of $True or do not specify a value, scheduled tasks begin within 30 minutes, before or after, the scheduled time. If you randomize the start times, it can distribute the impact of scanning. For example, if several virtual machines share the same host, randomized start times prevents all the hosts from starting the scheduled tasks at the same time.")] boolean RandomizeScheduleTaskTimes;
    [Write, Description("Indicates whether to enable behavior monitoring. If you specify a value of $True or do not specify a value, Windows Defender enables behavior monitoring")] boolean DisableBehaviorMonitoring;
    [Write, Description("Indicates whether to configure network protection against exploitation of known vulnerabilities. If you specify a value of $True or do not specify a value, network protection is enabled")] boolean DisableIntrusionPreventionSystem;
    [Write, Description("Indicates whether Windows Defender scans all downloaded files and attachments. If you specify a value of $True or do not specify a value, scanning downloaded files and attachments is enabled. ")] boolean DisableIOAVProtection;
    [Write, Description("Indicates whether to use real-time protection. If you specify a value of $True or do not specify a value, Windows Defender uses real-time protection. We recommend that you enable Windows Defender to use real-time protection.")] boolean DisableRealtimeMonitoring;
    [Write, Description("Specifies whether to disable the scanning of scripts during malware scans.")] boolean DisableScriptScanning;
    [Write, Description("Indicates whether to scan archive files, such as .zip and .cab files, for malicious and unwanted software. If you specify a value of $True or do not specify a value, Windows Defender scans archive files.")] boolean DisableArchiveScanning;
    [Write, Description("Indicates whether to disable the Automatic Exclusions feature for the server.")] boolean DisableAutoExclusions;
    [Write, Description("Indicates whether Windows Defender runs catch-up scans for scheduled full scans. A computer can miss a scheduled scan, usually because the computer is turned off at the scheduled time. If you specify a value of $True, after the computer misses two scheduled full scans, Windows Defender runs a catch-up scan the next time someone logs on to the computer. If you specify a value of $False or do not specify a value, the computer does not run catch-up scans for scheduled full scans.")] boolean DisableCatchupFullScan;
    [Write, Description("Indicates whether Windows Defender runs catch-up scans for scheduled quick scans. A computer can miss a scheduled scan, usually because the computer is off at the scheduled time. If you specify a value of $True, after the computer misses two scheduled quick scans, Windows Defender runs a catch-up scan the next time someone logs onto the computer. If you specify a value of $False or do not specify a value, the computer does not run catch-up scans for scheduled quick scans. ")] boolean DisableCatchupQuickScan;
    [Write, Description("Indicates whether Windows Defender parses the mailbox and mail files, according to their specific format, in order to analyze mail bodies and attachments. Windows Defender supports several formats, including .pst, .dbx, .mbx, .mime, and .binhex. If you specify a value of $True, Windows Defender performs email scanning. If you specify a value of $False or do not specify a value, Windows Defender does not perform email scanning. ")] boolean DisableEmailScanning;
    [Write, Description("Indicates whether to scan for malicious and unwanted software in removable drives, such as flash drives, during a full scan. If you specify a value of $True, Windows Defender scans removable drives during any type of scan. If you specify a value of $False or do not specify a value, Windows Defender does not scan removable drives during a full scan. Windows Defender can still scan removable drives during quick scans or custom scans.")] boolean DisableRemovableDriveScanning;
    [Write, Description("Indicates whether to disable scanning of restore points.")] boolean DisableRestorePoint;
    [Write, Description("Indicates whether to scan mapped network drives. If you specify a value of $True, Windows Defender scans mapped network drives. If you specify a value of $False or do not specify a value, Windows Defender does not scan mapped network drives.")] boolean DisableScanningMappedNetworkDrivesForFullScan;
    [Write, Description("Indicates whether to scan for network files. If you specify a value of $True, Windows Defender scans network files. If you specify a value of $False or do not specify a value, Windows Defender does not scan network files. We do not recommend that you scan network files.")] boolean DisableScanningNetworkFiles;
    [Write, Description("Indicates whether to disable UI lockdown mode. If you specify a value of $True, Windows Defender disables UI lockdown mode. If you specify $False or do not specify a value, UI lockdown mode is enabled.")] boolean UILockdown;
    [Write, Description("Specifies an array of the actions to take for the IDs specified by using the ThreatIDDefaultAction_Ids parameter.")] uint64 ThreatIDDefaultAction_Ids;
    [Write, Description("Specifies which automatic remediation action to take for an unknonwn level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String ThreatIDDefaultAction_Actions;
    [Write, Description("Specifies which automatic remediation action to take for a low level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String UnknownThreatDefaultAction;
    [Write, Description("Specifies which automatic remediation action to take for a low level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String LowThreatDefaultAction;
    [Write, Description("Specifies which automatic remediation action to take for a moderate level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String ModerateThreatDefaultAction;
    [Write, Description("Specifies which automatic remediation action to take for a high level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String HighThreatDefaultAction;
    [Write, Description("Specifies which automatic remediation action to take for a severe level threat."), ValueMap{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}, Values{"Allow","Block","Clean","NoAction","Quarantine","Remove","UserDefined"}] String SevereThreatDefaultAction;
    [Write, Description("Specifies how Windows Defender checks for user consent for certain samples. If consent has previously been granted, Windows Defender submits the samples. Otherwise, if the MAPSReporting parameter does not have a value of Disabled, Windows Defender prompts the user for consent."), ValueMap{"Allways Prompt","Send safe samples automatically","Never send","Send all samples automatically"}, Values{"Allways Prompt","Send safe samples automatically","Never send","Send all samples automatically"}] String SubmitSamplesConsent;
};

