#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0.0"), FriendlyName("WebDeploy")]
class MSFT_xWebdeploy : OMI_BaseResource
{
    [Key, Description("Path to Web Deploy package (zip format).")] String PackagePath;
    [Key, Description("Path to Web Site (content path or site name).")] String ContentPath;	
    [Write, Description("Desired state of resource."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

