[ClassVersion("1.0.0"),FriendlyName("xMySqlDatabase")] 
class MSFT_xMySqlDatabase : OMI_BaseResource
{
    [Key, Description("Name of the database.")] String DatabaseName;
    [Write, Description("Should the database be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("The root credential that is used to install MySql server."), EmbeddedInstance("MSFT_Credential")] String RootCredential;
    [Required, Description("MYSql Version Number")] String MySqlVersion;
};


